[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path = 'forge-cache'
fuzz = { runs = 1_000 }
gas_reports = ["*"]

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[etherscan]
goerli = { key = "${API_KEY_ETHERSCAN}" }
mainnet = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
localhost = "http://localhost:8545"
goerli = "https://eth-goerli.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"


# See more config options https://book.getfoundry.sh/reference/config.html
